"""column: email column add at todo table

Revision ID: 38dfd297e65f
Revises: 4f7ed94938d0
Create Date: 2023-04-15 14:44:30.074794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38dfd297e65f'
down_revision = '4f7ed94938d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('email', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'email')
    # ### end Alembic commands ###
